package com.aniapi.dreamsubanime.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF843daf)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFf6d8ff)
val md_theme_light_onPrimaryContainer = Color(0xFF2f004b)
val md_theme_light_secondary = Color(0xFF00668a)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFc0e8ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001e2c)
val md_theme_light_tertiary = Color(0xFF6b5e00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfce426)
val md_theme_light_onTertiaryContainer = Color(0xFF201c00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1e1a1d)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1e1a1d)
val md_theme_light_surfaceVariant = Color(0xFFeadfea)
val md_theme_light_onSurfaceVariant = Color(0xFF4b444d)
val md_theme_light_outline = Color(0xFF7c747d)
val md_theme_light_inverseOnSurface = Color(0xFFf7eef3)
val md_theme_light_inverseSurface = Color(0xFF342f33)

val md_theme_dark_primary = Color(0xFFe7b3ff)
val md_theme_dark_onPrimary = Color(0xFF4e0078)
val md_theme_dark_primaryContainer = Color(0xFF692094)
val md_theme_dark_onPrimaryContainer = Color(0xFFf6d8ff)
val md_theme_dark_secondary = Color(0xFF73d1ff)
val md_theme_dark_onSecondary = Color(0xFF003549)
val md_theme_dark_secondaryContainer = Color(0xFF004d68)
val md_theme_dark_onSecondaryContainer = Color(0xFFc0e8ff)
val md_theme_dark_tertiary = Color(0xFFdec800)
val md_theme_dark_onTertiary = Color(0xFF383100)
val md_theme_dark_tertiaryContainer = Color(0xFF514700)
val md_theme_dark_onTertiaryContainer = Color(0xFFfce426)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1a1d)
val md_theme_dark_onBackground = Color(0xFFe9e0e5)
val md_theme_dark_surface = Color(0xFF1e1a1d)
val md_theme_dark_onSurface = Color(0xFFe9e0e5)
val md_theme_dark_surfaceVariant = Color(0xFF4b444d)
val md_theme_dark_onSurfaceVariant = Color(0xFFcdc3cd)
val md_theme_dark_outline = Color(0xFF978e98)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1a1d)
val md_theme_dark_inverseSurface = Color(0xFFe9e0e5)

val seed = Color(0xFF8d46b8)
val error = Color(0xFFba1b1b)